server:
  port:  9998


spring:
  servlet:
    multipart:
#      是否支持多文件上传
      enabled: true
      max-file-size: 1MB
      max-request-size: 1MB
#      上传文件的保存地址 --VUE 项目路径里面的地址
      location: C:\Users\admin\Desktop\Git仓库\coding-test\element-project\src\assets\
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/503test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update

  #sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: true

#日志详细度的控制
#logging:
#  level:
#    root: warn
#    net.lzzy.practices: debug

